# Generated by Django 5.2.8 on 2025-11-18 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='rut_persona',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='RUT sólo puede contener dígitos, guion (-) o punto (.)', regex='^[0-9\\-.]+$')]),
        ),
    ]
